### ISSUE TITLE
where to put gatsby-config.js

### ISSUE THREAD

**Issue by kraxli** [gera2ld/gatsby-remark-markmap#1]
Hi 
this feature looks great but I could not make it run. Maybe it is because I did not put  `gatsby-config.js` into the right directory. What is / are the right place(s) to put it? 
Thanks
Davd

**Comment by gera2ld** [comment]
`gatsby-config.js` is in the root directory of your project. Please take a look at the [Gatsby document](https://www.gatsbyjs.org/docs/).
